language: csharp
mono: none
dotnet: 2.0.0
solution: ./src/Styxz.Assetyard.sln
install:
  - dotnet restore ./src/Styxz.Assetyard.sln
script:
  - dotnet build ./src/
  - find . -maxdepth 3 -name “*Test.csproj” -type f | xargs dotnet test
