language: csharp
mono: none
dotnet: 2.0.0
solution: ./src/Styxz.Assetyard.sln
install:
  - dotnet restore ./src/Styxz.Assetyard.sln
script:
  - dotnet build ./src/
  - find . -maxdepth 4 -type f -name "*Tests.csproj" | xargs dotnet test
after_success:
  - bash <(curl -s https://codecov.io/bash)
